dateModified: 1723084153
email:
  fromEmail: mwurquha@gmail.com
  fromName: 'Test Site'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    ba847553-389d-48f1-ba0b-d307e74f2b86: 'Test Site' # Test Site
    cb17981e-6dff-47bd-b616-e2d9deb0cb52: 'Test Site' # Test Site
system:
  edition: solo
  live: true
  name: 'Test Site'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
